Link to VALIDATION.md and CLEANUP.md
common-voice/sentence-collector pull request #427
Opened 2021-04-12 11:38 UTC by bact

Add language validation/cleanup links to "Get Involved" section.

2021-04-12 15:44 UTC, MichaelKohler requested changes
Thanks, I like the idea! I've added one comment with a suggestion.

2021-04-12 15:44 UTC, MichaelKohler commented on README.md
> +- To add new language or adjust sentence validation/cleanup: see [VALIDATION.md](https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/VALIDATION.md) and [CLEANUP.md](htt
"To add a new language" seems confusing to me, as that only refers to validation and cleanup, not actually adding a new language to contribute to. What do you think of the following?

```suggestion
- To add or adjust validation and cleanup for a language see [VALIDATION.md](https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/VALIDATION.md) and [CLEANUP.md](https://github.com/common-voice/sentence-collector/blob/main/server/lib/cleanup/CLEANUP.md). Cleanup is optional and should only be used in rare cases.
```

2021-04-13 02:40 UTC, bact commented
Thanks for the suggestion. I agree with that.

2021-04-13 06:54 UTC, MichaelKohler approved these changes

2021-04-13 06:54 UTC, MichaelKohler commented
Thank you!

2021-04-13 06:54 UTC, merged

2021-04-17 12:20 UTC, MichaelKohler commented
:tada: This PR is included in version 2.3.4 :tada:

The release is available on [GitHub release](https://github.com/common-voice/sentence-collector/releases/tag/v2.3.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: