Localization: Removed placeholder strings in issue #518
common-voice/sentence-collector pull request #520
Opened 2021-11-02 15:47 UTC by HarikalarKutusu

This PR handles https://github.com/common-voice/sentence-collector/issues/518
+ Some minor changes in en/sentence-collector.ftl

2021-11-02 22:19 UTC, MichaelKohler commented
Thanks for tackling this. The code changes look good to me. The tests are now failing because we need to do https://github.com/common-voice/sentence-collector/issues/496. I will have a look at that tomorrow. I will also test your PR tomorrow.

2021-11-03 19:24 UTC, MichaelKohler requested changes
Thanks, I've noticed a bug (see comments) below. Apart from that it looks good functionality-wise as well.

Could you please also run prettier with `npm run format` and commit the changes?

I have set up the test infrastructure so it uses the real localization mechanism. If you want, you can rebase your branch on top of latest main and have a look at the tests. Some tests will still fail due to string changes. Would be great if you could get the tests to pass after that on your branch as well. If you want me to do that, that's fine too.

2021-11-03 21:40 UTC, HarikalarKutusu commented on web/src/components/confirm-form.tsx
> -            &nbsp;
Done...

2021-11-03 21:43 UTC, HarikalarKutusu commented
@MichaelKohler I've done the commit but I don't know how to approach your automatic testing routines. I'll be busy in the next ~3 days so if you can handle these it will be much quicker...

2021-11-05 22:59 UTC, MichaelKohler commented
You can run `npm test` locally to run all the automated tests. If you do that you will see the following errors:

```
should render loading notice

...Unable to find an element with the text: Loading rejected sentences... 
```

This you changed that to "Loading rejected sentences…", so a simple change in the string we test for is fine:

```
expect(screen.getByText('Loading rejected sentences…')).toBeTruthy();
```

This is the case for both `my-sentences-list.test.tsx` as well as `rejected-sentences.test.tsx`.

```
should render delete error

... Unable to find an element with the text: Failed to delete selected sentences.. Please try again!.
```

Also a changed string. Same solution as above to adjust the text we're testing against.

The `review-criteria.test.tsx` snapshot changed due to the criteria string updates, all changes there look good as well, so updating the test snapshot is the way to go: `npm test -- -u`.

2021-11-05 23:02 UTC, MichaelKohler approved these changes
Thank you!

2021-11-05 23:03 UTC, merged

2021-11-07 00:55 UTC, MichaelKohler commented
:tada: This PR is included in version 2.12.2 :tada:

The release is available on [GitHub release](https://github.com/common-voice/sentence-collector/releases/tag/v2.12.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: